pipeline {
    stages {

      stage('Build and Push image') {
        build 'KMTBuildAndPush'
      }

      stage('Deploy') {
        build 'KMTDeploy'
      }

      stage('Test deployed KMT App') {
        build 'KMTTest'
      }
   }
}
