/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 15-Feb-2018 6:09:40 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "UserRole" CASCADE
;

DROP TABLE IF EXISTS "User" CASCADE
;

DROP TABLE IF EXISTS "State" CASCADE
;

DROP TABLE IF EXISTS "LKP_UserRole" CASCADE
;

DROP TABLE IF EXISTS "LKP_State" CASCADE
;

DROP TABLE IF EXISTS "LKP_Category" CASCADE
;

DROP TABLE IF EXISTS "LKP_ActionState" CASCADE
;

DROP TABLE IF EXISTS "LKP_Action" CASCADE
;

DROP TABLE IF EXISTS "Feedback" CASCADE
;

DROP TABLE IF EXISTS "ArticleViewCount" CASCADE
;

DROP TABLE IF EXISTS "Article" CASCADE
;

/* Create Tables */

CREATE TABLE "UserRole"
(
	"userRoleID" integer NOT NULL,
	"userID" varchar(10)	 NULL,
	"categoryID" integer NULL
)
;

CREATE TABLE "User"
(
	"userID" varchar(10)	 NOT NULL,
	"userFirstName" varchar(50)	 NOT NULL,
	"userLatName" varchar(50)	 NOT NULL,
	"userMiddleName" varchar(50)	 NULL,
	"stateID" integer NULL,
	"articleViewID" integer NULL
)
;

CREATE TABLE "State"
(
	"stateID" integer NOT NULL,
	"articleID" integer NULL,
	"lkpStateID" integer NULL,
	"actionStateID" integer NULL
)
;

CREATE TABLE "LKP_UserRole"
(
	"userRoleID" integer NOT NULL,
	"userRoleName" varchar(50)	 NOT NULL,
	"userRoleDesc" varchar(500)	 NULL
)
;

CREATE TABLE "LKP_State"
(
	"lkpStateID" integer NOT NULL,
	"stateName" varchar(50)	 NOT NULL,
	"stateDesc" varchar(500)	 NOT NULL
)
;

CREATE TABLE "LKP_Category"
(
	"categoryID" integer NOT NULL,
	"categoryDesc" varchar(500)	 NOT NULL,
	"categoryName" varchar(100)	 NOT NULL
)
;

CREATE TABLE "LKP_ActionState"
(
	"actionStateID" integer NOT NULL,
	"actionID" integer NULL,
	"stateID" integer NULL,
	"userRoleID" integer NULL
)
;

CREATE TABLE "LKP_Action"
(
	"actionID" integer NOT NULL,
	"actionName" varchar(50)	 NOT NULL,
	"actionDesc" varchar(500)	 NOT NULL
)
;

CREATE TABLE "Feedback"
(
	"feedbackID" integer NOT NULL,
	"rating" integer NULL,
	"comment" varchar(2000)	 NULL,
	"articleID" integer NULL,
	"userID" varchar(10)	 NULL
)
;

CREATE TABLE "ArticleViewCount"
(
	"articleViewCountID" integer NOT NULL,
	"viewCount" integer NOT NULL,
	"articleID" integer NULL
)
;

CREATE TABLE "Article"
(
	"articleID" integer NOT NULL,
	"articleTitle" varchar(200)	 NOT NULL,
	"articleDesc" varchar(500)	 NOT NULL,
	"articlePath" varchar(500)	 NOT NULL,
	"articleContent" text NULL,
	"categoryID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "UserRole" ADD CONSTRAINT "PK_Table2"
	PRIMARY KEY ("userRoleID")
;

CREATE INDEX "IXFK_UserRole_LKP_Category" ON "UserRole" ("categoryID" ASC)
;

CREATE INDEX "IXFK_UserRole_LKP_UserRole" ON "UserRole" ("userRoleID" ASC)
;

CREATE INDEX "IXFK_UserRole_User" ON "UserRole" ("userID" ASC)
;

ALTER TABLE "User" ADD CONSTRAINT "PK_Table2"
	PRIMARY KEY ("userID")
;

CREATE INDEX "IXFK_User_ArticleView" ON "User" ("articleViewID" ASC)
;

CREATE INDEX "IXFK_User_State" ON "User" ("stateID" ASC)
;

ALTER TABLE "State" ADD CONSTRAINT "PK_Table2"
	PRIMARY KEY ("stateID")
;

CREATE INDEX "IXFK_State_Article" ON "State" ("articleID" ASC)
;

CREATE INDEX "IXFK_State_LKP_ActionState" ON "State" ("actionStateID" ASC)
;

ALTER TABLE "LKP_UserRole" ADD CONSTRAINT "PK_LKP_UserRole"
	PRIMARY KEY ("userRoleID")
;

ALTER TABLE "LKP_State" ADD CONSTRAINT "PK_Table2"
	PRIMARY KEY ("lkpStateID")
;

ALTER TABLE "LKP_Category" ADD CONSTRAINT "PK_Table1"
	PRIMARY KEY ("categoryID")
;

ALTER TABLE "LKP_ActionState" ADD CONSTRAINT "PK_LKP_ActionState"
	PRIMARY KEY ("actionStateID")
;

CREATE INDEX "IXFK_ActionState_Action" ON "LKP_ActionState" ("actionID" ASC)
;

CREATE INDEX "IXFK_ActionState_State" ON "LKP_ActionState" ("stateID" ASC)
;

CREATE INDEX "IXFK_LKP_ActionState_LKP_UserRole" ON "LKP_ActionState" ("userRoleID" ASC)
;

ALTER TABLE "LKP_Action" ADD CONSTRAINT "PK_Action"
	PRIMARY KEY ("actionID")
;

ALTER TABLE "Feedback" ADD CONSTRAINT "PK_Approver"
	PRIMARY KEY ("feedbackID")
;

CREATE INDEX "IXFK_ArticleView_Article" ON "Feedback" ("articleID" ASC)
;

CREATE INDEX "IXFK_Feedback_User" ON "Feedback" ("userID" ASC)
;

ALTER TABLE "ArticleViewCount" ADD CONSTRAINT "PK_ArticleViewCount"
	PRIMARY KEY ("articleViewCountID")
;

CREATE INDEX "IXFK_ArticleViewCount_Article" ON "ArticleViewCount" ("articleID" ASC)
;

ALTER TABLE "Article" ADD CONSTRAINT "PK_Table2"
	PRIMARY KEY ("articleID")
;

CREATE INDEX "IXFK_Article_Category" ON "Article" ("categoryID" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "UserRole" ADD CONSTRAINT "FK_UserRole_LKP_Category"
	FOREIGN KEY ("categoryID") REFERENCES "LKP_Category" ("categoryID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "UserRole" ADD CONSTRAINT "FK_UserRole_LKP_UserRole"
	FOREIGN KEY ("userRoleID") REFERENCES "LKP_UserRole" ("userRoleID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "UserRole" ADD CONSTRAINT "FK_UserRole_User"
	FOREIGN KEY ("userID") REFERENCES "User" ("userID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "User" ADD CONSTRAINT "FK_User_State"
	FOREIGN KEY ("stateID") REFERENCES "State" ("stateID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "State" ADD CONSTRAINT "FK_State_Article"
	FOREIGN KEY ("articleID") REFERENCES "Article" ("articleID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "State" ADD CONSTRAINT "FK_State_LKP_ActionState"
	FOREIGN KEY ("actionStateID") REFERENCES "LKP_ActionState" ("actionStateID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "LKP_ActionState" ADD CONSTRAINT "FK_ActionState_Action"
	FOREIGN KEY ("actionID") REFERENCES "LKP_Action" ("actionID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "LKP_ActionState" ADD CONSTRAINT "FK_ActionState_State"
	FOREIGN KEY ("stateID") REFERENCES "LKP_State" ("lkpStateID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "LKP_ActionState" ADD CONSTRAINT "FK_LKP_ActionState_LKP_UserRole"
	FOREIGN KEY ("userRoleID") REFERENCES "LKP_UserRole" ("userRoleID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Feedback" ADD CONSTRAINT "FK_ArticleView_Article"
	FOREIGN KEY ("articleID") REFERENCES "Article" ("articleID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Feedback" ADD CONSTRAINT "FK_Feedback_User"
	FOREIGN KEY ("userID") REFERENCES "User" ("userID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "ArticleViewCount" ADD CONSTRAINT "FK_ArticleViewCount_Article"
	FOREIGN KEY ("articleID") REFERENCES "Article" ("articleID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Article" ADD CONSTRAINT "FK_Article_Category"
	FOREIGN KEY ("categoryID") REFERENCES "LKP_Category" ("categoryID") ON DELETE No Action ON UPDATE No Action
;
